name: CI/CD with DockerHub

on:
  push:
    branches:
      - lab_work_5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker-compose -f lab_work_5/src/Docker-compose.yml up -d
          # docker exec -ti auth go test    
          # docker run -d test
          # docker-compose -f docker-compose.yml exec auth npm test
          # Дополните этот шаг, чтобы запустить тесты вашего приложения

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker tag docker.io/library/src_server kataevy/src-server     
          docker push kataevy/src-server   
